<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('doctors', function (Blueprint $table) {
            $table->id();
            $table->foreignId('practice_id')->constrained();
            $table->string('doctor_key' , 20)->nullable()->unique();             // e.g: doctor-1234
            $table->enum('suffix', ['Miss', 'Mrs', 'Ms', 'Mr'])->nullable();
            $table->string('first_name' , 30)->nullable();
            $table->string('middle_name' , 30)->nullable();
            $table->string('last_name' , 30)->nullable();
            $table->string('primary_email')->unique()->nullable();
            $table->string('secondary_email')->nullable();
            $table->string('password')->nullable();
            $table->enum('gender', ['Male', 'Female', 'Transgender', 'Prefer not to say', 'Other'])->nullable();
            $table->date('dob')->nullable();
            $table->string('profile_photo_url')->nullable();
            $table->string('profile_photo_url_thumbnail')->nullable();
            $table->text('about_me')->nullable();
            $table->string('country_code_primary_phone_number' , 10)->nullable();
            $table->string('primary_phone_number' , 15)->nullable();
            $table->string('country_code_secondary_phone_number' , 10)->nullable();
            $table->string('secondary_phone_number' , 15)->nullable();
            $table->string('license_photo_url')->nullable();
            $table->string('passport_photo_url')->nullable();
            $table->string('emirate_photo_url')->nullable();
            $table->enum('marital_status', ['Unknown','Married','Single','Divorced','Separated','Widowed','Partner'])->nullable();
            $table->longText('kyc_verification_url')->nullable();       // KYC verification link generated by ShuftiPro
            $table->text('kyc_reference_no')->nullable();           // KYC verification reference no for doctor
            $table->longText('kyc_response')->nullable();           // KYC response for respective doctor
            $table->string('kyc_declined_status')->nullable();           // KYC decline statuses (if any)
            $table->enum('kyc_status', ['Pending', 'Invalid', 'Canceled', 'Timeout', 'Unauthorized', 'Accepted',
                            'Declined', 'Verification status is changed', 'Request deleted', 'Request received', 'Review pending'])->default('Accepted');
            $table->boolean('account_registration')->default(0);  // 0 => no (default), 1 => yes
            $table->boolean('draft_status')->default(0);  // 0 => no (default), 1 => yes
            $table->boolean('is_first_login')->default(1);  // 1 => yes, 0 => no
            $table->boolean('is_password_reset')->default(0);  // 0 => no, 1 => yes
            $table->boolean('is_active')->default(1);  // 0 => no, 1 => yes
            $table->string('created_by' , 20)->nullable();
            $table->string('updated_by' , 20)->nullable();
            $table->softDeletes();
            $table->timestamps();
            $table->rememberToken();
            $table->index(['practice_id', 'doctor_key', 'primary_email', 'kyc_status', 'is_active']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('doctors');
    }
};
